name: Install, Test and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        uses: actions/npm@master
        with:
          args: ci
      - name: Test
        uses: actions/npm@master
        with:
          args: test
      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_REGISTRY_URL: https://npm.pkg.github.com/zyhou
        with:
          args: publish
