name: Install, Test and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        uses: actions/npm@master
        with:
          args: install
      - name: Test
        uses: actions/npm@master
        with:
          args: test
      - name: Publish
        uses: actions/npm@master
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
          NPM_REGISTRY_URL: @zyhou:registry=https://npm.pkg.github.com
        with:
          args: publish
